package whodarr.classic.organizer.webarchive

import whodarr.classic.episodeinfo.{EpisodeId, EpisodeRecognizer}
import whodarr.classic.organizer.{SerialFilenameConverter, SerialFilenameSanitizer}

class WebArchiveSerialFilenameConverter(episodeRecognizer: EpisodeRecognizer) extends SerialFilenameConverter, SerialFilenameSanitizer:

  override def convertEpisodeFilename(filename: String): String =
    val serialDesignation = filename.split(" - ")(1).split(" ")(0)
    val sanitizedFilename = sanitizeFilename(filename)

    val episodeId = episodeRecognizer.detectFromPath(filename)

    if episodeId.isEmpty then
      sanitizedFilename
    else
      sanitizedFilename.replace(serialDesignation, formatEpisodeDesignation(episodeId.get))

  private def formatEpisodeDesignation(episodeId: EpisodeId) : String =
    s"S${"%02d".format(episodeId.seasonNumber)}E${"%02d".format(episodeId.episodeNumber)}"


  /**
   * Removes ".autogenerated" from filenames.
   *
   * @param filename The filename to sanitize.
   * @return The sanitized filename.
   */
  override def sanitizeFilename(filename: String): String =
    filename.replace(".autogenerated", "")
