package whodarr.classic.episodeinfo.webarchive.tests

import org.scalatest.flatspec.AnyFlatSpec
import whodarr.classic.episodeinfo.{EpisodeId, EpisodeRecognizer}
import whodarr.classic.episodeinfo.webarchive.WebArchiveSimpleEpisodeRecognizer

class WebArchiveOrganizerTests extends AnyFlatSpec {
  "WebArchive Simple Recognizer" should "recognize simple episode name" in {
    // Arrange
    val recognizer: EpisodeRecognizer = WebArchiveSimpleEpisodeRecognizer(10) // Offset by 10 episodes

    // Act / Assert
    assert(recognizer.detectFromPath(
      "Doctor Who - S08E03 (057) - The Claws of Axos (1).mp4").get === EpisodeId(8, 11)
    )

    // With extra in filename
    assert(recognizer.detectFromPath(
      "Doctor Who - S08E03 (057) - The Claws of Axos (2).autogenerated.vtt").get === EpisodeId(8, 12))
  }
}