package whodarr.classic.organizer.webarchive.tests

import org.scalatest.flatspec.AnyFlatSpec
import whodarr.classic.organizer.SerialFilenameSanitizer
import whodarr.classic.organizer.webarchive.WebArchiveSerialFilenameConverter

//    val mockFolder = EchoSerialFolder(List("Doctor Who - S08E03 (057) - The Claws of Axos (1).avi"), List("Doctor Who - S08E03 (057) - The Claws of Axos (2).autogenerated.txt"))

class WebArchiveTests extends AnyFlatSpec {
  "WebArchive Sanitizer" should "remove .autogenerated from file names" in {
    // Arrange
    // Note: For the time being, these parameters aren't necessary for the sanitizing functionality.
    val sanitizer: SerialFilenameSanitizer = WebArchiveSerialFilenameConverter("S08E03", 10, 57)

    // Act / Assert
    assert(sanitizer.sanitizeFilename(
      "Doctor Who - S08E03 (057) - The Claws of Axos (2).autogenerated.vtt") ===
      "Doctor Who - S08E03 (057) - The Claws of Axos (2).vtt")
    assert(sanitizer.sanitizeFilename(
      "Doctor Who - S08E03 (057) - The Claws of Axos (3).autogenerated.txt") ===
      "Doctor Who - S08E03 (057) - The Claws of Axos (3).txt")
  }
}