@startuml

cloud "Doctor Who Episode API"
cloud "WebArchive"

package "Classic Whodarr" {
    [daemon] --> [downloader]
    [daemon] --> [watcher]
    [downloader] --> [episodeinfo]
    [watcher] --> [episodeinfo]
    [cli] --> [organizer]
    [daemon] --> [organizer]
}

node "Media Playing Services" {
    [Plex]
    [Jellyfin]
}

node "Downloading Services" {
    [qBitTorrent]
}

[episodeinfo] --> "Doctor Who Episode API"
"Downloading Services" --> "WebArchive"

[downloader] --> "Downloading Services"

[watcher] --> "Media Playing Services"

@enduml