name: Scala CI (Windows)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Scala (sbt) (based on Adoptium)
        uses: olafurpg/setup-scala@v10

      - name: Run tests
        run: sbt test

      # Optional: This step uploads information to the GitHub dependency graph and unblocking Dependabot alerts for the repository
      - name: Upload dependency graph
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: scalacenter/sbt-dependency-submission@ab086b50c947c9774b70f39fc7f6e20ca2706c91
